apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "konga.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "konga.name" . }}
    helm.sh/chart: {{ include "konga.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if .Values.config }}
  HOST: "{{ default 0.0.0.0 .Values.config.host }}"
  PORT: "{{ default 1337 .Values.config.port }}"
  NODE_ENV: {{ default "development" .Values.config.node_env }}
  SSL_KEY_PATH: {{ .Values.config.ssl_key_path }}
  SSL_CRT_PATH: {{ .Values.config.ssl_crt_path }}
  KONGA_HOOK_TIMEOUT: "{{ default 60000 .Values.config.konga_hook_timeout }}"
  DB_ADAPTER: {{ default "postgres" .Values.config.db_adapter }}
  DB_URI: {{ .Values.config.db_uri }}
  DB_HOST: {{ default "localhost" .Values.config.db_host }}
  DB_PORT: "{{ default 5432 .Values.config.db_port }}"
  DB_USER: {{ .Values.config.db_user }}
  DB_PASSWORD: {{ .Values.config.db_password }}
  DB_DATABASE: {{ default "konga" .Values.config.db_database }}
  DB_PG_SCHEMA: {{ default "public" .Values.config.db_pg_schema }}
  {{- if eq .Values.config.node_env "development" }}
  KONGA_LOG_LEVEL: {{ default "debug" .Values.config.log_level }}
  {{ else if eq .Values.config.node_env "production" }}
  KONGA_LOG_LEVEL: {{ default "warn" .Values.config.log_level }}
  {{- end }}
  TOKEN_SECRET: {{ .Values.config.token_secret }}
  {{- end }}